from dataclasses import dataclass

from src.llm.context_builder import (
    MemoryContext
)

from src.llm.llm_client import (
    LLMClient,
    LLMResponse
)


@dataclass
class GeneratedResponse:
    """
    Final response generated by the LLM.

    The original memory context is retained so that
    downstream components can inspect what was supplied
    to the model.
    """

    text: str

    llm_response: LLMResponse

    context: MemoryContext


class ResponseGenerator:
    """
    Generates conversational responses using a
    provider-independent LLMClient.

    This component is responsible only for prompt
    construction and response generation.

    It does not perform retrieval or memory mutation.
    """

    def __init__(
        self,
        llm_client: LLMClient
    ):
        self.llm_client = llm_client

    # GENERATE RESPONSE

    def generate(
        self,
        query: str,
        context: MemoryContext
    ) -> GeneratedResponse:
        """
        Generate a response using the supplied query
        and already-constructed memory context.
        """

        if not query.strip():
            raise ValueError(
                "query cannot be empty"
            )

        if context is None:
            raise ValueError(
                "context cannot be None"
            )

        prompt = self._build_prompt(
            query=query,
            context=context
        )

        response = self.llm_client.generate(
            prompt=prompt,
            system_prompt=self._system_prompt()
        )

        return GeneratedResponse(
            text=response.text,
            llm_response=response,
            context=context
        )



    @staticmethod
    def _system_prompt() -> str:
        """
        System instructions for conversational response
        generation.
        """

        return (
            "You are a conversational AI assistant "
            "with access to retrieved memories. "
            "Use the provided memories when they are "
            "relevant to the user's question. "
            "Do not invent facts or memories. "
            "If the available memory does not contain "
            "the requested information, say so clearly."
        )

    # PROMPT CONSTRUCTION

    @staticmethod
    def _build_prompt(
        query: str,
        context: MemoryContext
    ) -> str:
        """
        Construct the final prompt sent to the LLM.

        The memory context is inserted exactly as supplied
        by ContextBuilder.
        """

        return (
            "Relevant conversational memory:\n\n"
            f"{context.text}\n\n"
            "User question:\n\n"
            f"{query}\n\n"
            "Answer the user's question using the "
            "relevant memory above. "
            "Do not invent information."
        )